[package]
name = "bruss_config"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.8"
lazy_static = "1.4"
serde = "1.0"
mongodb = { workspace = true }
tt = { path = "../tt" }
bruss_data = { path = "../data" }

